name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('go/go.sum') }}

      - name: Download and verify dependencies
        working-directory: ./go
        run: |
          go mod download
          go mod verify

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

      - name: Lint
        working-directory: ./go
        run: |
          go vet ./...
          golangci-lint run --timeout=2m

      - name: Build
        working-directory: ./go
        run: go build ./...

      - name: Test
        working-directory: ./go
        run: go test -race -cover ./...

      - name: Coverage Report
        working-directory: ./go
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Check module tidiness
        working-directory: ./go
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum || (echo "go.mod or go.sum is not clean" && exit 1)
